// AUTO-GENERATED by tools/gen_spaces.py — do not edit by hand.
// Display metadata for common-area spaces: the sheet's own name,
// the governing plan and its context note, keyed by space number.
export const SPACE_META = {
  "001": {
    "floor": 1,
    "name": "Vestibule",
    "note": "doors 001A/001B; canopy above at entry",
    "sheet": "A100"
  },
  "003": {
    "floor": 1,
    "name": "Lobby",
    "note": "door 003",
    "sheet": "A100"
  },
  "004": {
    "floor": 1,
    "name": "Reception",
    "note": "no door tag - open to lobby",
    "sheet": "A100"
  },
  "005": {
    "floor": 1,
    "name": "Market",
    "note": "Home2 Market; open",
    "sheet": "A100"
  },
  "006": {
    "floor": 1,
    "name": "Breakfast",
    "note": "doors 006A/006B",
    "sheet": "A100"
  },
  "007": {
    "floor": 1,
    "name": "Food Prep",
    "note": "doors 007A/007B",
    "sheet": "A100"
  },
  "008": {
    "floor": 1,
    "name": "Dry Storage",
    "note": "door 008",
    "sheet": "A100"
  },
  "009": {
    "floor": 1,
    "name": "Servery",
    "note": "open to breakfast",
    "sheet": "A100"
  },
  "010": {
    "floor": 1,
    "name": "Work Stations",
    "note": "door 010",
    "sheet": "A100"
  },
  "011": {
    "floor": 1,
    "name": "Managers Office",
    "note": "door 011",
    "sheet": "A100"
  },
  "012": {
    "floor": 1,
    "name": "Closet",
    "note": "door 012",
    "sheet": "A100"
  },
  "013": {
    "floor": 1,
    "name": "Laundry Discharge",
    "note": "doors 013A/013B; 01/A450 linen chute callout",
    "sheet": "A100"
  },
  "014": {
    "floor": 1,
    "name": "Employee Breakroom",
    "note": "door 014",
    "sheet": "A100"
  },
  "015": {
    "floor": 1,
    "name": "Laundry",
    "note": "doors 015A/015B",
    "sheet": "A100"
  },
  "016": {
    "floor": 1,
    "name": "Dryer Room",
    "note": "door 016",
    "sheet": "A100"
  },
  "017": {
    "floor": 1,
    "name": "Open Storage",
    "note": "no door tag; Delta-4 cloud",
    "sheet": "A100"
  },
  "018": {
    "floor": 1,
    "name": "Meeting Room",
    "note": "doors 018A/018B",
    "sheet": "A100"
  },
  "019": {
    "floor": 1,
    "name": "WOMENS",
    "note": "public restroom off lobby corridor; door 019. Printed with NO apostrophe on A100 - not normalised. A520 prints further variants, see conflicts",
    "sheet": "A100"
  },
  "020": {
    "floor": 1,
    "name": "MEN'S",
    "note": "public restroom off lobby corridor; door 020",
    "sheet": "A100"
  },
  "021": {
    "floor": 1,
    "name": "Engineer",
    "note": "office, NOT a restroom, despite sitting in the 019/020 wall run; door 021",
    "sheet": "A100"
  },
  "022": {
    "floor": 1,
    "name": "Sales",
    "note": "door 022",
    "sheet": "A100"
  },
  "023": {
    "floor": 1,
    "name": "Fitness Room",
    "note": "door 023; equipment by others",
    "sheet": "A100"
  },
  "024": {
    "floor": 1,
    "name": "Guest Laundry",
    "note": "no door tag on A100",
    "sheet": "A100"
  },
  "025": {
    "floor": 1,
    "name": "Mech.",
    "note": "door 025; near Stair 2",
    "sheet": "A100"
  },
  "027": {
    "floor": 1,
    "name": "Unisex",
    "note": "public unisex restroom; door 027",
    "sheet": "A100"
  },
  "028": {
    "floor": 1,
    "name": "Elev. Eq.",
    "note": "elevator equipment room; door 028; 01/A432",
    "sheet": "A100"
  },
  "029": {
    "floor": 1,
    "name": "Meeting Rm. Sto.",
    "note": "door 029",
    "sheet": "A100"
  },
  "030": {
    "floor": 1,
    "name": "Mech. / Plumb. Room",
    "note": "doors 030A/030B; WH, WS, BP in room",
    "sheet": "A100"
  },
  "031": {
    "floor": 1,
    "name": "PBX",
    "note": "door 031",
    "sheet": "A100"
  },
  "032": {
    "floor": 1,
    "name": "Housekeeping",
    "note": "doors 032A/032B. One word on floor 1; 'House Keeping' two words on floors 2-4",
    "sheet": "A100"
  },
  "033": {
    "floor": 1,
    "name": "Electrical",
    "note": "door 033; main electrical / MDP room this floor",
    "sheet": "A100"
  },
  "100": {
    "floor": 1,
    "name": "Stair 1",
    "note": "doors 100A/100B; 01/A430",
    "sheet": "A100"
  },
  "121": {
    "floor": 1,
    "name": "Guest Corridor",
    "note": "doors 121A/121B",
    "sheet": "A100"
  },
  "137": {
    "floor": 1,
    "name": "Elev. Lobby",
    "note": "door 137",
    "sheet": "A100"
  },
  "139": {
    "floor": 1,
    "name": "Ice Machine",
    "note": "alcove; no door tag",
    "sheet": "A100"
  },
  "140": {
    "floor": 1,
    "name": "Elev.",
    "note": "ONLY elevator number on A100 but TWO hoistways drawn - do not invent 140A/140B",
    "sheet": "A100"
  },
  "141": {
    "floor": 1,
    "name": "Stair 2",
    "note": "door 141; 01/A440, 01/A432",
    "sheet": "A100"
  },
  "200": {
    "floor": 2,
    "name": "Stair 1",
    "note": "door 200; window type I; 02/A430, 02/A431",
    "sheet": "A101"
  },
  "219": {
    "floor": 2,
    "name": "Electrical",
    "note": "door 219; W4/W8",
    "sheet": "A101"
  },
  "220": {
    "floor": 2,
    "name": "Storage",
    "note": "door 220; W4; adjacent clouded X-hatched shaft tagged 05/A425, unnamed",
    "sheet": "A101"
  },
  "221": {
    "floor": 2,
    "name": "Guest Corridor",
    "note": "single double-loaded corridor, 247'-11 1/4\" long",
    "sheet": "A101"
  },
  "235": {
    "floor": 2,
    "name": "House Keeping",
    "note": "door 235; linen chute 02/A450",
    "sheet": "A101"
  },
  "237": {
    "floor": 2,
    "name": "Elevator Lobby",
    "note": "door 237; W6/W3",
    "sheet": "A101"
  },
  "239": {
    "floor": 2,
    "name": "Ice Machine",
    "note": "alcove opposite the elevator lobby",
    "sheet": "A101"
  },
  "240": {
    "floor": 2,
    "name": "Elev.",
    "note": "TWO cabs under one number; 02/A440",
    "sheet": "A101"
  },
  "241": {
    "floor": 2,
    "name": "Stair 2",
    "note": "door 241; window type I; 02/A431",
    "sheet": "A101"
  },
  "300": {
    "floor": 3,
    "name": "Stair 1",
    "note": "door 300; 02/A430",
    "sheet": "A102"
  },
  "319": {
    "floor": 3,
    "name": "Electrical",
    "note": "door 319; W4/W8; 04/A425",
    "sheet": "A102"
  },
  "320": {
    "floor": 3,
    "name": "Storage",
    "note": "door 320; W4; unnamed clouded chute/shaft at the 319/320 boundary; 05/A425",
    "sheet": "A102"
  },
  "321": {
    "floor": 3,
    "name": "Guest Corridor",
    "note": "full length; clear width 5'-1 3/4\"",
    "sheet": "A102"
  },
  "335": {
    "floor": 3,
    "name": "House Keeping",
    "note": "door 335; 02/A450",
    "sheet": "A102"
  },
  "337": {
    "floor": 3,
    "name": "Elevator Lobby",
    "note": "door 337; W3/W6",
    "sheet": "A102"
  },
  "339": {
    "floor": 3,
    "name": "Ice Machine",
    "note": "no door tag; 07/A425 adjacent",
    "sheet": "A102"
  },
  "340": {
    "floor": 3,
    "name": "Elev.",
    "note": "TWO cars under one number; 02/A440",
    "sheet": "A102"
  },
  "341": {
    "floor": 3,
    "name": "Stair 2",
    "note": "door 341; 02/A431",
    "sheet": "A102"
  },
  "400": {
    "floor": 4,
    "name": "Stair 1",
    "note": "west stair; door tag 400; 02/A430",
    "sheet": "A103"
  },
  "419": {
    "floor": 4,
    "name": "Electrical",
    "note": "door 419; W4/W8",
    "sheet": "A103"
  },
  "420": {
    "floor": 4,
    "name": "Storage",
    "note": "door 420; W4",
    "sheet": "A103"
  },
  "421": {
    "floor": 4,
    "name": "Guest Corridor",
    "note": "single corridor, full length of floor",
    "sheet": "A103"
  },
  "435": {
    "floor": 4,
    "name": "House Keeping",
    "note": "door 435; 02/A450",
    "sheet": "A103"
  },
  "437": {
    "floor": 4,
    "name": "Elevator Lobby",
    "note": "door 437; W6",
    "sheet": "A103"
  },
  "439": {
    "floor": 4,
    "name": "Ice Machine",
    "note": "east end, off elevator lobby",
    "sheet": "A103"
  },
  "440": {
    "floor": 4,
    "name": "Elev.",
    "note": "CORRECTED 2026-08-07 - A103 draws TWO cars side by side under the single number 440, identical to 140/240/340. Do not invent 440A/440B",
    "sheet": "A103"
  },
  "441": {
    "floor": 4,
    "name": "Stair 2",
    "note": "east stair; door 441; 02/A431",
    "sheet": "A103"
  },
  "ZONE-A": {
    "floor": 1,
    "name": "Entry / Porte-Cochere Outdoor Lounge",
    "note": "Exterior FF&E zone, not a numbered room on room_map.md. ffe-public.md flag 6: Zone A and Zone B are separate packages with separate rows - never summed.",
    "sheet": "ID-1.9"
  },
  "ZONE-B": {
    "floor": 1,
    "name": "Pool Deck / Patio",
    "note": "Exterior FF&E zone, not a numbered room on room_map.md. AS104 is Rev 5 dated 04/09/26 - the newest sheet in the set; see ffe-public.md.",
    "sheet": "ID-1.7"
  }
};
