// gen_seed_mep.mjs — emit js/seed-mep.js, the demo-mode MEP punch fixture.
//
// The demo DB carries exactly one guest room (101), so it carries exactly one
// punch doc: 101-MEP, with its REAL content straight out of
// tools/out/mep/101-MEP.json. Nothing here is invented — the only edits are a
// handful of demo check-offs and one open issue, so the board and the phone
// both show a punch list mid-walk rather than a wall of empty boxes.
//
// Why not seed all sixteen floor-1 lists: this file is precached in the service
// worker SHELL and ships to every phone. One doc is ~50 KB; sixteen would be
// most of a megabyte of demo data riding on crew cell plans forever. Tests that
// need a fuller grid inject synthetic docs at runtime (tests/mep-ui.mjs does
// exactly this) rather than growing the shipped fixture.
//
//   node tools/gen_seed_mep.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SRC = join(HERE, 'out', 'mep', '101-MEP.json');
const OUT = join(ROOT, 'js', 'seed-mep.js');

const doc = JSON.parse(readFileSync(SRC, 'utf8'));

// Demo state, applied by SORT ORDER so it is stable across content rebuilds:
// the first four mechanical lines walked and signed, one plumbing line flagged.
// Initials match the FF&E demo fixture's crew so the board's "check-offs by
// person" panel does not sprout a stranger.
const ordered = Object.entries(doc.items)
  .sort((a, b) => (a[1].sort || 0) - (b[1].sort || 0));

const CHECKS = [
  { i: 0, ini: 'AJ' }, { i: 1, ini: 'AJ' }, { i: 2, ini: 'RM' }, { i: 3, ini: 'RM' },
];
const ISSUE = { i: 6, text: 'thermostat reads 8 deg high — needs recalibration' };

for (const { i, ini } of CHECKS) {
  const it = ordered[i] && ordered[i][1];
  if (!it) continue;
  it.checked = true;
  it.initials = ini;
  it.checkedByName = '';
  it.checkedByUid = 'demo';
  it.checkedAt = null;
  it.checkedAtLocal = null;
}
const iss = ordered[ISSUE.i] && ordered[ISSUE.i][1];
if (iss) { iss.issue = ISSUE.text; iss.issueResolved = false; }

const out = {
  ...doc,
  createdAt: '2026-08-11T12:00:00.000Z',
  updatedAt: null,
};

const body = JSON.stringify({ [doc.number]: out }, Object.keys(out).length ? null : null, 2)
  .split('\n').map(l => '  ' + l).join('\n').trimStart();

writeFileSync(OUT,
`// AUTO-GENERATED by tools/gen_seed_mep.mjs — DO NOT EDIT BY HAND.
//
// Demo-mode fixture for the MEP punch surface: room 101's REAL punch list
// (${ordered.length} lines across five trades, built by tools/build_mep.mjs from the
// M/E/P/FP sheets), with four demo check-offs and one open issue applied so the
// screens show a walk in progress. Every label, mark, source citation, location
// and punch step is the shipped content, unedited.
//
// It rides the same rooms map as the guest rooms and the common areas; the
// \`mep-punch\` type slug is what keeps the three populations apart (js/util.js).
export function seedMep() {
  return ${body};
}
`);
console.log(`js/seed-mep.js written — ${ordered.length} punch lines, `
  + `${CHECKS.length} demo check-offs, 1 open issue`);
